version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Go mod bot configurations
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
  # Docker bot configurations
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
